name: Build Teensy 4.1 Firmware

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install PlatformIO
        run: pip install platformio

      - name: Build firmware
        run: platformio run --environment teensy41

      - name: Upload firmware artifact
        uses: actions/upload-artifact@v4
        with:
          name: teensy41-firmware
          path: .pio/build/teensy41/firmware.hex

      - name: Upload build log
        uses: actions/upload-artifact@v4
        with:
          name: build-log
          path: .pio/build/teensy41/*.log
